# Generated by Django 4.2.2 on 2023-07-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizevariant',
            old_name='color_name',
            new_name='size_name',
        ),
    ]
