# Generated by Django 4.2.2 on 2023-07-13 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_color_name_sizevariant_size_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageVariant',
            fields=[
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_num', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
        migrations.AddField(
            model_name='product',
            name='storage_variant',
            field=models.ManyToManyField(to='products.storagevariant'),
        ),
    ]
