# Generated by Django 4.2.2 on 2023-07-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_storagevariant_storage_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagevariant',
            old_name='price',
            new_name='price_extra',
        ),
        migrations.RemoveField(
            model_name='colorvariant',
            name='price',
        ),
        migrations.AlterField(
            model_name='storagevariant',
            name='storage_num',
            field=models.IntegerField(),
        ),
    ]
