# Generated by Django 4.2.2 on 2023-07-14 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_storagevariant_storage_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uui', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=1000)),
                ('minimum_amount', models.IntegerField(default=9000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
